# version: routeconfig/v1
# kind: RouteConfig

# ------------------------ Services ------------------------

services:
  user-profile:
    upstream:
      scheme: http
      host: mock-upstream
      port: 8082

# ------------------------ Routes ------------------------

routes:

  - name: user-profile
    service: user-profile
    match:
      path_prefix: /api/v1/profile
      methods: [GET]
      headers:
        Authorization: []
        X-Request-Id: []
        X-Client-Channel: [web, mobile]
        X-Device-Id: []
        X-Correlation-Id: []
    policies:
      - name: security-headers


# ------------------------ Policies ------------------------

policies:

  headers:

    security-headers:
      request:
        add:
          X-Request-Id: "<generated-or-from-incoming>"
        remove:
          - X-Forwarded-For
          - X-Forwarded-Proto

      response:
        add:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
        remove:
          - Server


