# ------------------------ Services ------------------------

services:
  user-profile:
    upstream:
      scheme: http
      host: mock-upstream
      port: 8082

  order-service:
    upstream:
      scheme: http
      host: mock-upstream
      port: 8083

  benchmark:
    upstream:
      scheme: http
      host: mock-upstream
      port: 8082

# ------------------------ Routes ------------------------

routes:

  - name: user-profile
    service: user-profile
    match:
      path_prefix: /api/v1/profile
      methods: [GET]
      headers:
        Authorization: []
        X-Request-Id: []
        X-Client-Channel: [web, mobile]
        X-Device-Id: []
        X-Correlation-Id: []
    policies:
      - name: security-headers
      - name: profile-rate-limit

  - name: user-orders
    service: order-service
    match:
      path_prefix: /api/v1/orders
      methods: [GET]
      headers:
        Authorization: [ ]
        X-Request-Id: [ ]
        X-Client-Channel: [ web, mobile ]
        X-Device-Id: [ ]
        X-Correlation-Id: [ ]
    policies:
      - name: security-headers
      - name: order-rate-limit

  - name: benchmark
    service: benchmark
    match:
      path_prefix: /benchmark
      methods: [GET]

# ------------------------ Policies ------------------------

policies:

  headers:

    security-headers:
      request:
        add:
          X-Request-Id: "<generated-or-from-incoming>"
        remove:
          - X-Forwarded-For
          - X-Forwarded-Proto

      response:
        add:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
        remove:
          - Server

  rate_limits:

    profile-rate-limit:
      rate: 100
      burst: 1

    order-rate-limit:
      rate: 20
      burst: 10
